name: first workflow
on: workflow_dispatch:
  - main

jobs:
  job1:
    runs-on: ubuntu latest
    steps:
      - name: start echo
        run: echo "job1 start"
      - name: end echo
        run: echo"job1 end"
